stages:
  - testing

test:
  stage: testing
  image: 1maa/php-dev:8.1
  script:
    - composer install
    - php vendor/bin/phpunit --verbose

metrics:
  stage: testing
  image: 1maa/php-dev:8.1
  script:
    - composer install
    - php vendor/bin/phpunit --verbose
    - php vendor/bin/phpmetrics  --junit=./build/phpunit/junit.xml --report-html=./build/phpmetrics .
  artifacts:
    paths:
      - build/phpunit/
      - build/phpmetrics/
    expire_in: 1 day
