on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: 1maa/php-dev:8.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: Run Linter
        run: php vendor/bin/php-cs-fixer fix -v --dry-run
      - name: Execute test suite
        run: composer test
      - name: Send coverage to Scrutinizer CI
        if: ${{ always() }}
        run: |
          git config --global --add safe.directory /__w/jelly/jelly
          php vendor/bin/ocular code-coverage:upload --format=php-clover build/phpunit/clover.xml
