on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: 1maa/php-dev:8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: Execute test suite
        run: composer test
      - name: Send coverage to Scrutinizer CI
        if: ${{ always() }}
        run: php vendor/bin/ocular code-coverage:upload --format=php-clover build/phpunit/clover.xml
